apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        # image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        image: frogmining/k8-php
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: ""
          - name: MYSQL_HOST
            value: mysql-read.default.svc.cluster.local
        livenessProbe:
          tcpSocket:
            port: 80
        resources:
{{ toYaml .Values.resources | indent 12 }}
